Landing_page/urls.py
from django.urls import path
from .views import  HomeInformation

app_name = 'homepage'

urlpatterns = [
    path('', HomeInformation.as_view(), name='information'),
]

account/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import Account, Information, GalleryList, GalleryDelete, GalleryCreate, SongsList, SongCreate,SongDelete, SongUpdate, VideoCreate, VideoDelete, VideosList, VideoUpdate, MessageList, MessageUpdate, MessageDelete, ProfileView, PasswordChange

app_name = "account"
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("password_change/", PasswordChange.as_view(), name="password_change"),
    path("password_change/done/", views.PasswordChangeDoneView.as_view(), name="password_change_done",),
    # path("password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    # path("password_reset/done/", views.PasswordResetDoneView.as_view(), name="password_reset_done",),
    # path("reset/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(), name="password_reset_confirm",),
    # path("reset/done/", views.PasswordResetCompleteView.as_view(), name="password_reset_complete",),
]

urlpatterns += [
    path("", Account.as_view(), name="dashboard"),
    path('profile/', ProfileView.as_view(), name='profile'),
    path("info/<int:pk>", Information.as_view(), name="info"),
    path("gallery/", GalleryList.as_view(), name="gallery"),
    path("gallery/create/", GalleryCreate.as_view(), name="gallery_create"),
    path("gallery/delete/<int:pk>", GalleryDelete.as_view(), name="gallery_delete"),
    path("song/", SongsList.as_view(), name="songs"),
    path("song/create/", SongCreate.as_view(), name="song_create"),
    path("song/update/<int:pk>", SongUpdate.as_view(), name="song_update"),
    path("song/delete/<int:pk>", SongDelete.as_view(), name="song_delete"),
    path("video/", VideosList.as_view(), name="videos"),
    path("video/create/", VideoCreate.as_view(), name="video_create"),
    path("video/update/<int:pk>", VideoUpdate.as_view(), name="video_update"),
    path("video/delete/<int:pk>", VideoDelete.as_view(), name="video_delete"),
    path("message/", MessageList.as_view(), name="message"),
    path("message/update/<int:pk>", MessageUpdate.as_view(), name="message_update"),
    path("message/delete/<int:pk>", MessageDelete.as_view(), name="message_delete"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Landing_page.urls')),
    path('account/', include('account.urls')),
]

if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    email = models.EmailField(unique=True)
    # is_author = models.BoolianField(default=False)
    # special_user = models.DateTimeField(default=timezone.now)

class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField()
    

class AccountHits(models.Model):
    date = models.DateField(null=True,unique=True)
    view_count = models.PositiveIntegerField(default=0)
    hits = models.ManyToManyField(IPAddress, blank=True, related_name="hits")
    # unique_ips = models.ManyToManyField('UniqueIP', blank=True)

account/forms.py
from django import forms
from .models import User
from Landing_page.models import ContactUs


class ContactForms(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ContactForms, self).__init__(*args, **kwargs)
        self.fields['subject'].disabled = True
        self.fields['name'].disabled = True
        self.fields['email'].disabled = True
        self.fields['message'].disabled = True

    class Meta:
        model = ContactUs
        fields = ['name', 'email', 'subject', 'message', 'status']


class ProfileForms(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        super(ProfileForms, self).__init__(*args, **kwargs)

        if user.is_superuser:
            self.fields['username'].disabled = True
            self.fields['email'].disabled = False
        else:
            self.fields['username'].disabled = True
            self.fields['email'].disabled = True

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

account/views.py
from django.shortcuts import render, redirect
from django.forms import inlineformset_factory
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import IPAddress, User, AccountHits
from Landing_page.models import MainData, Gallery, MusicPlayer, VideoPlayer, ContactUs, SocialLinks
from django.urls import reverse_lazy
from .forms import ContactForms, ProfileForms
from datetime import date
from datetime import datetime, timedelta


class Account(LoginRequiredMixin, ListView):
    model = AccountHits
    template_name = 'registration/account.html'
    # queryset = MusicPlayer.objects.all().count    

    def get_object(self):
        account_hits = AccountHits.objects.all()
        ip_address = self.request.user.ip_address
        if ip_address not in account_hits.hints.all():
            account_hits.hits.add(ip_address)
        return account_hits

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['music'] = MusicPlayer.objects.all().count
        context['video'] = VideoPlayer.objects.all().count
        context['message'] = ContactUs.objects.all().count
        context['account'] = IPAddress.objects.all().count
        today = datetime.now().date()
        seven_days_ago = today - timedelta(days=7)
        context['view_data'] = list(reversed(AccountHits.objects.filter(date__range=[seven_days_ago, today]).order_by('-date')[:7]))
        return context



class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'registration/profile.html'
    success_url = reverse_lazy('account:profile')
    form_class = ProfileForms

    def get_object(self):
        return User.objects.get(pk=self.request.user.pk)

    def get_form_kwargs(self):
        kwargs = super(ProfileView, self).get_form_kwargs()
        kwargs.update({
            'user': self.request.user
        })
        return kwargs


class PasswordChange(PasswordChangeView):
    success_url = reverse_lazy("account:password_change_done")


class Information(LoginRequiredMixin, UpdateView):
    template_name = 'registration/information.html'
    model = MainData
    fields = ['title', 'description', 'header_logo', 'footer_logo']
    success_url = reverse_lazy('account:info', kwargs={'pk': 1})
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        main_data = self.get_object()

        # Create a formset for SocialLinks
        SocialLinksFormSet = inlineformset_factory(MainData, SocialLinks, fields=['label', 'link'], extra=0, can_delete=False)

        # Check if there is POST data (form submission) and update the formset accordingly
        if self.request.method == 'POST':
            social_links_formset = SocialLinksFormSet(self.request.POST, instance=main_data)
        else:
            social_links_formset = SocialLinksFormSet(instance=main_data)

        context['social_links_formset'] = social_links_formset

        return context

    def form_valid(self, form):
        context = self.get_context_data()
        social_links_formset = context['social_links_formset']

        if form.is_valid() and social_links_formset.is_valid():
            # Save the changes to the MainData form
            main_data = form.save(commit=False)
            main_data.save()

            # Save the changes to the SocialLinks forms within the formset
            for social_links_form in social_links_formset:
                if social_links_form.cleaned_data:
                    social_links = social_links_form.save(commit=False)
                    social_links.main_data = main_data  # Set the relationship to the MainData instance
                    social_links.save()

            return redirect(self.success_url)

    # If the form or formset is not valid, re-render the form with errors
        return self.render_to_response(self.get_context_data(form=form, social_links_formset=social_links_formset))



# Gallery admin Panel -------------

class GalleryList(LoginRequiredMixin, ListView):
    model = Gallery
    template_name = 'registration/gallery_list.html'
    paginate_by = 10
    queryset = Gallery.objects.all().order_by("-created")

    
class GalleryCreate(LoginRequiredMixin, CreateView):
    model = Gallery
    template_name = 'registration/gallery_create.html'
    fields = ['title', 'data_file']


class GalleryDelete(LoginRequiredMixin, DeleteView):
    model = Gallery
    template_name = 'registration/gallery_form_delete.html'
    success_url = reverse_lazy('account:gallery')
    fields = ['title', 'data_file', 'created']


# Songs admin Panel -------------

class SongsList(LoginRequiredMixin, ListView):
    model = MusicPlayer
    template_name = 'registration/songs_list.html'
    paginate_by = 10
    queryset = MusicPlayer.objects.all().order_by("-created")

    
class SongCreate(LoginRequiredMixin, CreateView):
    model = MusicPlayer
    template_name = 'registration/song_create.html'
    fields = ['title', 'album', 'songwriter', 'cover_art', 'arrngement', 'image', 'audio_file', 'publish', 'status']


class SongUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'registration/song_create.html'
    model = MusicPlayer
    fields = ['title', 'album', 'songwriter', 'cover_art', 'arrngement', 'image', 'audio_file', 'publish', 'status']


class SongDelete(LoginRequiredMixin, DeleteView):
    model = MusicPlayer
    template_name = 'registration/song_form_delete.html'
    success_url = reverse_lazy('account:songs')
    fields = ['title', 'album', 'songwriter', 'cover_art', 'arrngement', 'image', 'audio_file', 'publish', 'status']


# Videos admin Panel -------------

class VideosList(LoginRequiredMixin, ListView):
    model = VideoPlayer
    template_name = 'registration/videos_list.html'
    paginate_by = 10
    queryset = VideoPlayer.objects.all().order_by("-created")

    
class VideoCreate(LoginRequiredMixin, CreateView):
    model = VideoPlayer
    template_name = 'registration/video_create.html'
    fields = ['title', 'album', 'director', 'cover_art', 'image', 'data_file', 'publish', 'status']


class VideoUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'registration/video_create.html'
    model = VideoPlayer
    fields = ['title', 'album', 'director', 'cover_art', 'image', 'data_file', 'publish', 'status']


class VideoDelete(LoginRequiredMixin, DeleteView):
    model = VideoPlayer
    template_name = 'registration/video_form_delete.html'
    success_url = reverse_lazy('account:videos')
    fields = ['title', 'album', 'director', 'cover_art', 'image', 'data_file', 'publish', 'status']


# Contact admin Panel -------------
class MessageList(LoginRequiredMixin, ListView):
    model = ContactUs
    template_name = 'registration/message_list.html'
    paginate_by = 10
    queryset = ContactUs.objects.all().order_by("-created")
    

class MessageUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'registration/message_update.html'
    model = ContactUs
    form_class = ContactForms


class MessageDelete(LoginRequiredMixin, DeleteView):
    model = ContactUs
    template_name = 'registration/message_delete.html'
    success_url = reverse_lazy('account:message')
    fields = ['name', 'email', 'subject', 'message', 'status']

templates/base/account/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Dashboard</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    <!-- Favicon -->
    <link rel="icon"  href="{% static "images/icons/favicon.ico" %}">
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <!-- Libraries Stylesheet -->
    <link href="{% static 'account/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'account/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />
    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'account/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Template Stylesheet -->
    <link href="{% static 'account/css/style.css' %}" rel="stylesheet">
</head>
<body>
    <div class="container-fluid position-relative d-flex p-0">
    {% include 'base/account/header.html' %}    
    {% block content%}{% endblock content %}
    {% include 'base/account/footer.html' %}
    </div>
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'account/js-lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'account/js-lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'account/js-lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'account/js-lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'account/js-lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'account/js-lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'account/js-lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <!-- Template Javascript -->
    <script src="{% static 'account/js/main.js' %}"></script>
</body>
</html>

templates/base/account/footer.html
<!-- Footer Start -->
    <div class="container-fluid pt-4 px-4">
        <div class="bg-secondary rounded-top p-4">
            <div class="row">
                <div class="col-12 col-sm-6 text-center text-sm-start">
                    &copy; <a href="{% url 'homepage:information' %}">Ehsan Ghorbanzadeh</a>, All Right Reserved. 
                </div>
                <div class="col-12 col-sm-6 text-center text-sm-end">
                    Designed By <a href="https://farzinshams.com">Farzin Shams</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->
</div>
<!-- Content End -->
<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

templates/base/account/header.html
{% load static %}
<!-- Spinner Start -->
<div id="spinner" class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
<!-- Spinner End -->
<!-- Sidebar Start -->
<div class="sidebar pe-4 pb-3">
    <nav class="navbar bg-secondary navbar-dark">
        <a href="{% url 'account:dashboard' %}" class="navbar-brand mx-4 mb-3">
            <h3 class="text-primary"><i class="fa fa-user-edit me-2"></i>Admin Panel</h3>
        </a>
        <div class="d-flex align-items-center ms-4 mb-4">
            <div class="position-relative">
                <img class="rounded-circle" src="{% static 'account/img/user.jpg' %}" alt="" style="width: 40px; height: 40px;">
                <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
            </div>
            <div class="ms-3">
                <h6 class="mb-0">{% if user.get_full_name %}{{ user.get_full_name|title }}{% else %}{{ user.username|title }}{% endif %}</h6>
                <span>Admin</span>
            </div>
        </div>
        <div class="navbar-nav w-100">
            <a href="{% url 'account:dashboard' %}" class="nav-item nav-link {% if request.resolver_match.url_name == 'dashboard' %}active{% endif %}"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle {% if request.resolver_match.url_name == 'gallery' %}active show{% elif request.resolver_match.url_name == 'gallery_create' %}active show{% endif %}" data-bs-toggle="dropdown" aria-expanded="{% if request.resolver_match.url_name == 'gallery' %}true{% elif request.resolver_match.url_name == 'gallery_create' %}true{% else %}false{% endif %}"><i class="fa fa-image me-2"></i>Gallery</a>
                <div class="dropdown-menu bg-transparent border-0 {% if request.resolver_match.url_name == 'gallery' %}show{% elif request.resolver_match.url_name == 'gallery_create' %}show{% endif %}">
                    <a href="{% url 'account:gallery' %}" class="dropdown-item {% if request.resolver_match.url_name == 'gallery' %}active{% endif %}">Gallery List</a>
                    <a href="{% url 'account:gallery_create' %}" class="dropdown-item {% if request.resolver_match.url_name == 'gallery_create' %}active{% endif %}">Add Image</a>
                </div>
            </div>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle {% if request.resolver_match.url_name == 'songs' %}active show{% elif request.resolver_match.url_name == 'song_create' %}active show{% elif request.resolver_match.url_name == 'song_update' %}active show{% endif %}" data-bs-toggle="dropdown" aria-expanded="{% if request.resolver_match.url_name == 'songs' %}true{% elif request.resolver_match.url_name == 'song_create' %}true{% elif request.resolver_match.url_name == 'song_update' %}true{% else %}false{% endif %}"><i class="fa fa-music me-2"></i>Songs</a>
                <div class="dropdown-menu bg-transparent border-0 {% if request.resolver_match.url_name == 'songs' %}show{% elif request.resolver_match.url_name == 'song_create' %}show{% elif request.resolver_match.url_name == 'song_update' %}show{% endif %}">
                    <a href="{% url 'account:songs' %}" class="dropdown-item {% if request.resolver_match.url_name == 'songs' %}active{% endif %}">Songs List</a>
                    <a href="{% url 'account:song_create' %}" class="dropdown-item {% if request.resolver_match.url_name == 'song_create' %}active{% endif %}">Add Song</a>
                </div>
            </div>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle {% if request.resolver_match.url_name == 'videos' %}active show{% elif request.resolver_match.url_name == 'video_create' %}active show{% elif request.resolver_match.url_name == 'video_update' %}active show{% endif %}" data-bs-toggle="dropdown" aria-expanded="{% if request.resolver_match.url_name == 'videos' %}true{% elif request.resolver_match.url_name == 'video_create' %}true{% elif request.resolver_match.url_name == 'video_update' %}true{% else %}false{% endif %}"><i class="fa fa-video me-2"></i>Videos</a>
                <div class="dropdown-menu bg-transparent border-0 {% if request.resolver_match.url_name == 'videos' %}show{% elif request.resolver_match.url_name == 'video_create' %}show{% elif request.resolver_match.url_name == 'video_update' %}show{% endif %}">
                    <a href="{% url 'account:videos' %}" class="dropdown-item {% if request.resolver_match.url_name == 'videos' %}active{% endif %}">Videos List</a>
                    <a href="{% url 'account:video_create' %}" class="dropdown-item {% if request.resolver_match.url_name == 'video_create' %}active{% endif %}">Add Video</a>
                </div>
            </div>
            <a href="{% url 'account:message' %}" class="nav-item nav-link {% if request.resolver_match.url_name == 'message' %}active{% elif request.resolver_match.url_name == 'message_update' %}active{% endif %}"><i class="fa fa-envelope me-2"></i>Messages</a>
            <a href="{% url 'account:info' pk=1 %}" class="nav-item nav-link {% if request.resolver_match.url_name == 'info' %}active{% endif %}"><i class="fa fa-table me-2"></i>Information</a>
            <a href="{% url 'account:profile' %}" class="nav-item nav-link {% if request.resolver_match.url_name == 'profile' %}active{% endif %}"><i class="fa fa-user me-2"></i>Profile</a>
        </div>
    </nav>
</div>
<!-- Sidebar End -->


<!-- Content Start -->
<div class="content">
    <!-- Navbar Start -->
    <nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
        <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
            <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
        </a>
        <a href="#" class="sidebar-toggler flex-shrink-0">
            <i class="fa fa-bars"></i>
        </a>
        <form class="d-none d-md-flex ms-4">
            <input class="form-control bg-dark border-0" type="search" placeholder="Search">
        </form>
        <div class="navbar-nav align-items-center ms-auto">
            <div class="nav-item dropdown">
                
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                    <img class="rounded-circle me-lg-2" src="{% static 'account/img/user.jpg' %}" alt="" style="width: 40px; height: 40px;">
                    <span class="d-none d-lg-inline-flex">{% if user.get_full_name %}{{ user.get_full_name|title }}{% else %}{{ user.username|title }}{% endif %}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                    <a href="{% url 'account:profile' %}" class="dropdown-item">My Profile</a>
                    <a href="{% url 'account:password_change' %}" class="dropdown-item">Change Password</a>
                    <a href="{% url 'account:logout' %}" class="dropdown-item">Log Out</a>
                </div>
            </div>
        </div>
    </nav>